export const RECEIVE_ALL_POSTS = "RECEIVE_ALL_POSTS";
export const INPUT_POST = "INPUT_POST";
export const UPDATE_INPUT_POST = 'UPDATE_INPUT_POST';

export const RECEIVE_ALL_MESSAGES = "RECEIVE_ALL_MESSAGES";
export const INPUT_MESSAGE = "INPUT_MESSAGE";
export const UPDATE_INPUT_MESSAGE = 'UPDATE_INPUT_MESSAGE';

export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const UPDATE_LOGIN_EMAIL = 'UPDATE_LOGIN_EMAIL';
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD';

export const SEARCH_USER = 'SEARCH_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const LOAD_NAVBAR = 'LOAD_NAVBAR';
